name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'DMG-${{ github.ref_name }}-Linux-amd64'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
            wails_os: 'linux'
          - name: 'DMG-${{ github.ref_name }}-Windows-amd64'
            platform: 'windows/amd64'
            os: 'windows-latest'
            wails_os: 'windows'
          - name: 'DMG-${{ github.ref_name }}-macOS'
            platform: 'darwin/universal'
            os: 'macos-latest'
            wails_os: 'darwin'
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

    - name: Tidy Go modules
      run: go mod tidy

    - name: Install Wails3 CLI
      run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

    - name: Check dependencies
      run: wails3 doctor

    - name: Build Wails project (Windows, Linux)
      if: matrix.os != 'macos-latest'
      run: wails3 task ${{ matrix.wails_os }}:package

    - name: Build Wails project (Darwin)
      if: matrix.os == 'macos-latest'
      run: wails3 task ${{ matrix.wails_os }}:package:universal

