name: Test Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

env:
  APP_NAME: pm2-manager

jobs:
  test-build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-amd64
          - os: macos-latest
            name: macos-universal
          - os: windows-latest
            name: windows-amd64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Wails3
      run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        # Xcode command line tools should be pre-installed on GitHub runners
        xcode-select --print-path || echo "Xcode tools not found"

    - name: Check dependencies
      run: wails3 doctor

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Test basic build
      run: |
        echo "Testing basic Go build..."
        go mod tidy
        go build -o test-binary .
        ls -la test-binary* || echo "No test binary found"
        
        echo "Testing Wails3 task system..."
        wails3 task common:generate:bindings || echo "Bindings generation failed"
        
        echo "Testing frontend build..."
        wails3 task common:build:frontend || echo "Frontend build failed"
        
        echo "Testing application build..."
        wails3 task build || echo "Application build failed"
        
        echo "Listing bin directory:"
        ls -la bin/ || echo "bin directory does not exist"

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs-${{ matrix.name }}
        path: |
          *.log
          build/*.log
        retention-days: 7
